services:
  - type: web
    name: classplus-extractor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: OWNER_ID
        value: your_user_id
      - key: CHANNEL_ID
        value: your_channel_id
